name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'woodpecker-cli/**'

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./woodpecker-cli
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        name: Build and push Docker image
        with:
          context: ./woodpecker-cli
          build-args: "VERSION=${{ env.VERSION }}"
          push: true
          tags: |
            ${{ env.REGISTRY }}/siroj100/woodpecker-cli:latest
            ${{ env.REGISTRY }}/siroj100/woodpecker-cli:${{ env.VERSION }}
